### ISSUE TITLE
Add badges to VSCode marketplace

### ISSUE THREAD

**Issue by tempit** [wix/stylable-intelligence#116]
Help me, @AlexShemeshWix , you're my only hope
https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_marketplace-presentation-tips

**Comment by tempit** [comment]
Both Travis and ApVeyor are on the approved list.

**Comment by AlexShemeshWix** [comment]
Im like...driving on 6 highway. Will do tomorrow?

**Comment by tempit** [comment]
Not urgent in any way. I put them back in the readme for now, seems to be working.

**Comment by tempit** [comment]
Added badges in proper readme. Closing.
