### ISSUE TITLE
Tests for CSS pass-through

### ISSUE THREAD

**Issue by tempit** [wix/stylable-intelligence#122]
CSS service is used/called at the connection level (in service.ts).
Unit tests are at the provider level, and so check only our logic.
There is one e2e test that checks for CSS completions as well, but other than that the CSS features we use are not tested.
Needed:
1. Integration tests or tests at the connection level to check CSS service usage. 
2. End to end tests that check results include CSS results as well (where needed).

**Comment by tomrav** [comment]
Several tests validate this behavior (color, completions, diagnostics...).
