### ISSUE TITLE
Auto format feature not configured for st.css files

### ISSUE THREAD

**Issue by tomrav** [wix/stylable-intelligence#134]
Trying to auto format (alt+shift+f, for me) any `.st.css` files returns the following error:
> Sorry, but there is no formatter for 'stylable'-files installed.

**Comment by tempit** [comment]
Looks like it's not part of VSCode CSS service, so the formatter you have is probably an extension. 
Find out which one it is (Beautify, in my case), and it's probably down to a simple PR to have them add us.

**Comment by tomrav** [comment]
Implemented formatting functionality, closing as resolved.
