### ISSUE TITLE
favicon logo in the list of languages in VSCode

### ISSUE THREAD

**Issue by arnonkehat** [wix/stylable-intelligence#149]
can we use the svg favicon logo in the list of languages?

![image](https://user-images.githubusercontent.com/8819912/34152421-313ec90a-e4b7-11e7-8783-4d51b40e475a.png)

![image](https://user-images.githubusercontent.com/8819912/34152443-445e3dae-e4b7-11e7-8f36-2bcf348789a2.png)

**Comment by tempit** [comment]
At present, there is no possibility for a custom language extension to add an icon, as icons are parts of icon themes, of which there are many. Should submit pull requests to popular themes. 

See https://github.com/Microsoft/vscode/issues/14662 for more details.

Closing, until such time as we can do something about this.
