### ISSUE TITLE
Custom selector coloring

### ISSUE THREAD

**Issue by lbelinsk** [wix/stylable-intelligence#153]
<img width="408" alt="screen shot 2017-12-24 at 4 26 50 pm" src="https://user-images.githubusercontent.com/18248989/34327213-71de6786-e8c7-11e7-93e1-3cbebd41e3df.png">

**Comment by tempit** [comment]
Can you tell me which VSCode color theme you are using?

**Comment by tempit** [comment]
Closing. Appears dead.
