### ISSUE TITLE
Add warning/error for unused named imports

### ISSUE THREAD

**Issue by hepiyellow** [wix/stylable-intelligence#243]

**Comment by tempit** [comment]
@hepiyellow 
1. Diagnostics are issued by Stylable (so they can be provided when building, etc.). In the future please open all diagnostics issues in the Stylable repo.
2. This is a known issue, the diagnostic is only provided once you try to use the import. See wix/stylable#379 for progress.
@tomrav

**Comment by tomrav** [comment]
Closing in favor of the same issue in [Stylable](https://github.com/wix/stylable/issues/393)
