### ISSUE TITLE
Missing error for `unknown var`

### ISSUE THREAD

**Issue by hepiyellow** [wix/stylable-intelligence#245]
Missing error for `unknown var` in some cases:

## Var decleration
Getting no error when D10 is not defined
```
:vars {
  headingText: value(D10);
}
```

## Mixin
Getting no error when R20 is not defined.

```
.root:skin(error) {
  -st-mixin: ToggleSwitchColor(
    colorUnchecked      value(R20),
  );
}
```

None of these variables are declared, but still I do not get any error about it.
I do get an error if I use a value not within a mixin call:
```
.root:focus-visible::track {
	box-shadow: 0 0 0 3px value(R20);
}

**Comment by tomrav** [comment]
Closing this issue, as it belongs in [Stylable](https://github.com/wix/stylable/issues/391).
