### ISSUE TITLE
fsevents exception crashes extension in vscode-insiders

### ISSUE THREAD

**Issue by tomrav** [wix/stylable-intelligence#272]
The latest version of `vscode-insiders` has an upgraded version of Electron which includes a newer version of Node.

Due to our dependency on `kissfs` and `webpack-watch`, we're getting an old version of `fsevents`. This version does not handle newer versions of node on OSX, and causes the extension to crash.

This has been temporarily fixed with a manual (and somewhat dirty) release, but requires additional attention to properly sort out.

**Comment by AviVahl** [comment]
Fixed in https://github.com/wix/stylable-intelligence/pull/273
