### ISSUE TITLE
Warning is displayed for mixin arguments with commas inside of them

### ISSUE THREAD

**Issue by alisey** [wix/stylable-intelligence#320]
Even though mixin arguments with commas inside of them were fixed in https://github.com/wix/stylable/pull/1164, Stylable Intelligence (ver 0.5.5) still thinks they are invalid:

<img src="https://user-images.githubusercontent.com/415252/82318596-cb3d4f80-99d8-11ea-8193-05c71f69992d.png" width="350">

**Comment by AviVahl** [comment]
will be fixed once `master` is released.

**Comment by tomrav** [comment]
`v0.5.6` has been published with the fix for this, thanks for opening the issue.
