### ISSUE TITLE
When extension installation fails - show error message

### ISSUE THREAD

**Issue by giladgrush** [wix/stylable-intelligence#67]
Scenario:
1) Visual Studio code version was not supported by extension
2) Installation succeeded, however 'reload' appeared on the extension and reloading did not work.

Solution:
Show an error message like the one below using the existing mechanism:

![image](https://user-images.githubusercontent.com/19182511/30060522-67c4c7e4-924c-11e7-8d64-355899556163.png)

**Comment by tempit** [comment]
This is entirely VSCode error reporting, no real way to interact with it. 
Closing.
