### ISSUE TITLE
Imports basing on tsconfig.json paths

### ISSUE THREAD

**Issue by jorge-armando** [wix/stylable-intelligence#930]
On .st.css files I can import another ones using custom paths defined inside of the tsconfig.json, under compilerOptions.paths, but the intelligence throws a error.

tsconfig.json
![image](https://user-images.githubusercontent.com/35030407/185718995-6d95a6e3-beb4-4ae8-976a-841235be2ec5.png)

-st-import
![image](https://user-images.githubusercontent.com/35030407/185719043-e7159558-6db2-4eea-ac66-71c36251b778.png)

It works on the webpack compile, but the intelligence does not recognize that it is a valid path, throwing this error: 
cannot resolve imported file: "@theme/components/atoms/Container/container.st.css"

**Comment by tomrav** [comment]
Thanks for trying out Stylable.

The `paths` option is a custom TypeScript resolution feature that Stylable is unaware of. In the case of building with webpack, what probably happens is that that the TypeScript integration is shared through webpack with the Stylable webpack-plugin.

As for the Stylable extension, it is not aware of what was defined in the webpack or TypeScript configs, and so the custom paths resolutions are not taken into consideration in the IDE. 

A possible solution we may offer, is passing a custom resolver to the Stylable configuration, and having that be picked up by the extension. But this approach would still require integrating some sort of resolver that supports `paths` from the user side.

If you can provide a small reproduction of your setup, or if the project is publicly accessible, I'd be glad to take a look and investigate further.

**Comment by jorge-armando** [comment]
The project is private, but I did a example here: https://github.com/jorge-armando/stylable-alias-issue

I understand. I don't know if it's possible, but the intelligence could inherit the paths defined in tsconfig.json or create an extra configuration inside stylable.config.js to insert the paths.

relative paths in large projects can become a headache for using too many "../../../.."

**Comment by tomrav** [comment]
Thank you for the reproduction case, we've started looking at it to see how it would behave under different solutions, and will update once we have more information.

**Comment by Scott-MacD** [comment]
I'm currently facing the same issue, but leveraging webpack resolver aliases - something like following:

```js
module.exports = {

    resolve: {
        alias: {
            "@components": path.resolve(__dirname, 'src/components/'),
            "@projects": path.resolve(__dirname, 'src/projects/')
        }
    },

};
```

It compiles just fine, but intelligence fails. A way to define this in the stylable config would work just fine for us.

**Comment by tomrav** [comment]
update: we've looked into this, and we think we can make it work for both TS paths and webpack aliases by adding a new resolver configuration to the `stylable.config.js` file. We're trying to make this as seamless as possible throughout our various integrations, and also add it to the stylable-intelligence extension automatically.

I hope to have more on this in the coming days.

**Comment by tomrav** [comment]
Exciting news! 
We just released new versions of Stylable and the Intelligence plugin that expose the ability to add a `stylable.config.js` file in the root of the project, and provide it with a `defaultConfig` that the plugin (and all integrations) can pick up.

Sorry for the delay on this, we ended up solving it a bit more thoroughly than originally thought. 

I tested this on your reproduction project (and a webpack alias one) and it seems to work fine locally for me, would love to hear that it works for you as well.

Example `stylable.config.js` config I used to test this out:
```js
const { createDefaultResolver } = require("@stylable/core");
const { TsconfigPathsPlugin } = require("tsconfig-paths-webpack-plugin");
const { typedConfiguration } = require("@stylable/cli");
// const { join } = require("path");

module.exports = {
  defaultConfig(fs) {
    return {
      resolveModule: createDefaultResolver(fs, {
        // alias: {
        //   "wp-alias": join(__dirname, "src/webpack-alias"),
        // },
        plugins: [
          new TsconfigPathsPlugin({
            configFile: require.resolve("./tsconfig.json"),
            extensions: [".st.css"],
          }),
        ],
      }),
    };
  },
  stcConfig: typedConfiguration({
    options: {
      srcDir: "./src",
      outDir: "./st-types",
      dts: true,
    },
  }),
};

```

> Note: the commented out lines are for using webpack aliasing functionality instead of TypeScript paths.

p.s. you may need to "Restart Extension Hosts" in VSCode, if the Intelligence plugin was already setup before you config your `stylable.config.js` file.

**Comment by tomrav** [comment]
Closing as we now offer the ability to configure this behavior for `stylable-intelligence`, please open an issue if something else doesn't appear to be working.
