### ISSUE TITLE
Create WebStorm\IntelliJ extension

### ISSUE THREAD

**Issue by qballer** [wix/stylable-intelligence#95]
It stands to reason that people using this extension would like support for other editors. It sounds to me that WebStorm should be our next runner up. Currently the problem with jetbrains editors that they don't support LSP. Other editors (or IDE's) should be considered: Eclipse, Atom, Sublime etc. We should also consider ODE support. 

CC: @tempit @idoros @nadavov

**Comment by tempit** [comment]
Changed comment, duplicating issue to differentiate WebStorm from LSP-compliant IDEs.

**Comment by tempit** [comment]
Closing. WIP, will have separate smaller issues as appropriate.
