### ISSUE TITLE
Create extensions for LSP-compliant editors

### ISSUE THREAD

**Issue by tempit** [wix/stylable-intelligence#96]
In alphabetical order:
Atom
Eclipse
Sublime
Vim (?)

**Comment by tempit** [comment]
Closing. Will be created as required, with separate issues.

**Comment by tomrav** [comment]
I'm afraid we haven't gotten to creating an official extension for vim (neovim, etc).

I do know that the vim ecosystem has several projects that act as adapters for LSP based language plugins (like ours).

Someone in our company (for their personal use) has previously successfully cloned this repo and wrapped it with such an adapter ([`coc.nvim`](https://github.com/neoclide/coc.nvim)),. 

We might get around to providing this, but it probably won't be in the immediate future - if you try to set it up for yourself, we'd be happy to try and help if you come across any issues.
